name = "toolxhub"
main = "./src/worker.ts"
compatibility_date = "2026-09-24"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "tools.fintechxhub.com", custom_domain = true }
]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "toolxhub-db"
database_id = "620cc37b-9136-4edd-a6a1-a3ecea68cfa0"
